import Head from "next/head";
import Navbar from "./navbar";
import Footer from "./footer"

// Layout acts as a wrapper for our entire website, and children represent
// different pages (we pass in a page one at a time as Layout's child,
// take a look at _app.js file)
function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}

export default Layout;
